name: Publish pre-release extension to 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      BUILD_FLAGS: '--pre-release'

  upload:
    needs: call-build
    runs-on: ubuntu-latest
    steps:       
  
      - name: download-artifacts
        uses: actions/download-artifact@v4
        with:
          name: VS Code extension VSIXes (ubuntu-latest)
      
      - name: upload extension
        run: |
          echo ${{ secrets.VSCE_PASSWORD }} | vsce login ${{ secrets.VSCE_USER }}
          vsce publish --pre-release  --packagePath ./out/vsix/*
          vsce logout




